In [22]:
import torch
a = torch.tensor([1,2,3])
b = torch.tensor([1,1,1])
print(a)
print(a.shape)
print(b.T)
print(a*b)
print(torch.dot(a,b.T))


tensor([1, 2, 3])
torch.Size([3])
tensor([1, 1, 1])
tensor([1, 2, 3])
tensor(6)
